services:
  arma3-tacops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_NAME: tacops
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        MODPACK_PATH: "Custom/TacOps_3_26062026.html"
    image: arma3-tacops:latest
    container_name: arma3-tacops
    network_mode: host
    volumes:
      - /home/arma3server/missions:/home/arma3server/serverfiles/mpmissions
      - /home/arma3server/mods:/home/arma3server/.local/share/Steam/steamapps/workshop/content/107410
    restart: unless-stopped
    stop_grace_period: 60s
    secrets:
      - steam_user_password
      - steam_user
      - steam_password
secrets:
  steam_user_password:
    file: ./secrets/secrets-common
  steam_user:
    file: ./secrets/steam_user
  steam_password:
    file: ./secrets/steam_password